version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint taskcat
  build:
    commands:
      - cfn-lint main.yml
      - taskcat test run
artifacts:
  files:
    - '**/*'