skip_checks:
  - CKV_AWS_79    # Bỏ qua kiểm tra IMDSv1
  - CKV_AWS_126   # Bỏ qua kiểm tra detailed monitoring EC2
  - CKV_AWS_135   # Bỏ qua kiểm tra EBS optimized
  - CKV_AWS_8     # Bỏ qua kiểm tra EBS encryption
  - CKV_AWS_23    # Bỏ qua kiểm tra mô tả cho security group/rule
  - CKV_AWS_130   # Bỏ qua kiểm tra subnet public IP mặc định
  - CKV2_AWS_5    # Bỏ qua kiểm tra security group phải gắn với resource
  - CKV2_AWS_12   # Bỏ qua kiểm tra default security group restrict traffic
  - CKV2_AWS_11   # Bỏ qua kiểm tra VPC flow logging
  - CKV2_AWS_41   # Bỏ qua kiểm tra EC2 phải có IAM role