FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

RUN chmod +x /usr/local/bin/nest

RUN npm run build

EXPOSE 5000

CMD ["npm", "run", "start:prod"]
