name: 'Terraform Plan'
on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout          # scan Repository
        uses: actions/checkout@v4

      - name: Set up Python for Checkov
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov==3.2.0

      - name: Run Checkov scan
        run: checkov -d ./Lab02 --config-file ./.checkov.yml --show-config

      - name: set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./Lab02
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Lab02
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1