name: 'Terraform Plan'
on:
  pull_request: 

job:
  terraform:
    if: github.repository == 'Zquan315/NT548-DevOps-ThucHanh'
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull_request: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4